### ISSUE TITLE
Button wrapping on hero-list

### ISSUE THREAD

**Issue by fergusg** [johnpapa/ngrx-data-lab#12]
The delete buttons wrap horribly for me (Chrome@latest)
![selection_013](https://user-images.githubusercontent.com/760983/38305781-0e78fd4e-3806-11e8-8491-6b4666d04a7a.png)

(The other buttons are hidden under the blue bar)

Fix is to reset `margin-right` in `mixin.scss`

```
  button.delete-button {
    margin-right: 0;
    margin-top: 6px;
    order: 1;
  }
```

One day I'll learn the pull-request thinging,...

**Comment by johnpapa** [comment]
thanks for adding this issue. 

we updated a lot here recently. i think this is resolved. if not, please reopen
