### ISSUE TITLE
How is heroService.entities$ prepopulated?

### ISSUE THREAD

**Issue by dereklin** [johnpapa/ngrx-data-lab#16]
I followed the example and created a repo.   At line #21: https://github.com/dereklin/ngrx-data-lab/blob/master/src/app/heroes/heroes/heroes.component.ts

```
this.heroes$ = heroService.entities$;
```
The heroes are prepopulated when the app runs.

I don't see any prepopulation in the code.  How is this done?

For me, I want to manually prepopulate some entity data, without using the in-memory db.  How can this be done?

**Comment by dereklin** [comment]
Oh.  It's bootstrapping the AppDevModule instead of the AppModule

**Comment by dereklin** [comment]
This is a related issue: https://github.com/johnpapa/angular-ngrx-data/issues/132

**Comment by johnpapa** [comment]
yes closed via #132
