### ISSUE TITLE
"Single line of code" in README

### ISSUE THREAD

**Issue by maxbendick** [johnpapa/ngrx-data-lab#17]
Quoting from the README under "What we accomplished": 

> With ngrx-data you add a single line of code to store/entity-store.module.ts for each entity and that's it! You heard that right, one line!

I'm a little confused by this. It looks like each entity needs its own service (Step 4 of the lab). If those files aren't necessary, that'd be pretty sweet. They do look a little bit like boilerplate, after all. More explanation would be much appreciated in any case.

**Comment by johnpapa** [comment]
nice feedback, thanks.

you probably want a service whether you use ngrx-data or not. the service abstracts getting the data for you. 

but - i see your point. could we add one service for all entities? sure, but i think separation is nice. I generally like having a service that handles the basics (the one we show) then i extend or override it to do whatever else i need.

if you have ideas on how to explain this or if it's too much for a quick start, let us know

Ideally the docs for this topic would contain this info and we'd just link to it from the quickstart. best of both worlds.

closing for now - but feel free to make a PR to the docs for this and a PR here to link to it.
