### ISSUE TITLE
villain-list.component/hero-list.component trackBy Fn needs to be fixed.

### ISSUE THREAD

**Issue by jberall** [johnpapa/ngrx-data-lab#19]
In the villain-list.component/hero-list.component
The trackBy Function should first have the 
interface TrackByFunction<T> {
  (index: number, item: T): any
};

While the code still works as it returns the index, you might want to update the package.

  byId(villain: Villain) {
    console.log('here', index, villain)
    return villain.id;
  }
  byId(index: number, villain: Villain) {
    console.log('here', index, villain)
    return villain.id;
  }
`

**Comment by johnpapa** [comment]
thanks for adding this issue. 

we updated a lot here recently. i think this is resolved. if not, please reopen
