### ISSUE TITLE
Documentation Step 4

### ISSUE THREAD

**Issue by dfulgham** [johnpapa/ngrx-data-lab#21]
Is this supposed to be EntityCollectionServiceBase and EntityCollectionServiceFactory ?

```Step 4 - Simplify the Hero and Villain data services
ngrx-data handles getting and saving our data for us. Replace the contents of heroes/hero.service.ts with the following code.

import { Injectable } from '@angular/core';
import { **EntityServiceBase**, **EntityServiceFactory** } from 'ngrx-data';
import { Hero } from '../core';

@Injectable()
export class HeroService extends EntityServiceBase<Hero> {
  constructor(entityServiceFactory: EntityServiceFactory) {
    super('Hero', entityServiceFactory);
  }
}
```

**Comment by duard** [comment]
It dont work :-1:

**Comment by kichnan** [comment]
Taking a guess here that you are trying it on your actual app and not a clone of this sample app. If so, then, the likely cause is that this sample-app documentation (_and_ codebase) has not been updated (`ngrx-data\@1.0.0-alpha.17`) to the latest package (`@6.1.0-alpha.2` as of today). See the version number difference in the two `package.json` files.

For now, I guess we would have to rely on the official package's [documentation](https://github.com/johnpapa/angular-ngrx-data). NOTE: You may face several issues at the beginning. Check their [Issues](https://github.com/johnpapa/angular-ngrx-data/issues/) section for likely setup issues. Hope that helps.

**Comment by johnpapa** [comment]
we updated a lot here recently. i think this is resolved. if not, please reopen
