### ISSUE TITLE
Type in Readme.md

### ISSUE THREAD

**Issue by ckapilla** [johnpapa/ngrx-data-lab#8]
There is a typo in the provided CLI command:

ng g s store/ngrx-date-toast -m store/entity-store --spec false
should be
ng g s store/ngrx-data-toast -m store/entity-store --spec false

**Comment by johnpapa** [comment]
fixed, thanks https://github.com/johnpapa/ngrx-data-lab/commit/2e0d42e3556eb02ce9ef193c982d8bfb10e12804
